#!/usr/bin/env python
# -*- coding: utf8 -*-

a=input('zadej cislo: ')  # funkce input vrací číslo tj. int, float

#a=raw_input('zadej retezec') # funkce vrací řetězec
#a=int(a)


if a==0:
    print 'A je NULA'
    b='ANO'
else:
    print 'A je nenulové'
    b='NE'
print 'Tohle se napiše vždy'


while a != 0 :
    a=a-1
    print a
print 'A tohle je konec!!!'